# .Sec 5 OS

name: "Mustafa Sami Shams Eldin"

favoritesongs:
  - 'Imagine - John Lennon'
  - 'Bohemian Rhapsody - Queen'
  - 'Hotel California - Eagles'

favoritesongs: ['Imagine', 'Bohemian Rhapsody']

characteristic:
  age: 20
  height: 175
  skincolor: 'fair'

/////////////////////////////////////////////////////
on:
  push:
    /* Specify the branch to trigger actions */
    branches:
      - main

jobs:
  build:
    /* Specify the type of machine */
    runs-on: ubuntu-latest
    /* Array of steps */
    steps:
      - name: "Testing GitHub Actions"
        run: pwd
      - name: "Printing a test message"
        run: echo "Hello from Mustafa's workflow!"

/////////////////////////////////////////////////////
After creating the YAML file in GitHub, use the `git pull` command to sync it locally.
/////////////////////////////////////////////////////
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      /* Display folder contents without downloading files */
      - name: "Before displaying folder contents"
        run: ls
      /* Use a ready-made action to download repository files */
      - uses: actions/checkout@v3

      - name: "After displaying folder contents"
        run: ls
$ Why does the `.github` folder not exist?
  In Linux, folders starting with `.` are hidden.
  Use:
    ls -a
/////////////////////////////////////////////////////
To build an image:
  1. Log in to DockerHub:
     docker login --username "<your-username>" --password "<your-password>"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Login to DockerHub"
        run: docker login --username mostafa_shams --password your_password_here

$ This approach is not secure, as anyone can see your credentials.

///////////////////////////////////////////////////////
In GitHub -> Settings -> Secrets -> Actions:
1. Press **New Repository Secret**.
2. Add the following:
   - **DOCKER_USERNAME** (your DockerHub username).
   - **DOCKER_TOKEN** (your DockerHub token).

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Login to DockerHub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
////////////////////////////////////////////////////////

Build and push an image:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Login to DockerHub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
      - name: "Build Docker Image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-docker-image .
      - name: "Push Docker Image to DockerHub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image
/////////////////////////////////////////////////////////
task
